// app/[locale]/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "./context/userContext";
import { Providers } from "./providers";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Find an escort near me | Local independent escort services | Lovira",
  description: "Generated by create next app",
   icons: {
    icon: '/favicon.png',
    shortcut: '/favicon.png',
  },
};

// IMPORTANT: Générez les paramètres statiques
export function generateStaticParams() {
  return [
    { locale: 'en' },
    { locale: 'fr' }, 
    { locale: 'de' },
    { locale: 'es' },
    { locale: 'pt' }
  ];
}

export default async function LocaleLayout({ params, children }: { params: Promise<{ locale: string }>, children: ReactNode  }) {
  const { locale } = await params
  
  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers locale={locale}>
          <UserProvider>
            {children}
            <Toaster />
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}